export const sagaActions = {
  USER_SETUP_SAGA: 'USER_SETUP_SAGA',
  USER_LOGIN_SAGA: 'USER_LOGIN_SAGA',
  UPDATE_USER_SAGA: 'UPDATE_USER_SAGA',
  ADD_CAR_SAGA: 'ADD_CAR_SAGA',
  UPDATE_CAR_SAGA: 'ADD_CAR_SAGA',
  DELETE_CAR_SAGA: 'ADD_CAR_SAGA',
}
