export const FakeUpcomingEvents = [
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage: "https://wallpapercave.com/wp/wp6279032.jpg",
  },
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage:
    //   "https://wallpaperscart.com/wp-content/uploads/2021/11/Car-Backgrounds-Wallpapers-HD-4K_14-1024x640.jpg",
  },
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage: "https://wallpaper.dog/large/5495964.jpg",
  },
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage:
    //   "https://airwallpaper.com/wp-content/uploads/2016/10/Auto-Backgrounds-For-Desktop.jpg",
  },
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage: "https://img.wallpapersafari.com/desktop/1024/576/2/37/4s1kh9.jpg",
  },
  {
    eventLabel: "Next Event",
    title: "AUTO.RIA Race",
    date: "12.12.2021",
    address: "Kharkiv. Maidan constitution",
    discipline: "Digital motorsport.",
    status: "National Seria",
    series: "National Digital Time Attack Series (NS-CTA) 2021",
    // backgroundImage: "https://cdn.statically.io/img/wallpaperaccess.com/full/229228.jpg",
  },
];
